# Generated by Django 4.2.5 on 2025-08-30 07:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_prompt",
                    models.TextField(
                        help_text="User's input prompt for story generation"
                    ),
                ),
                (
                    "story_text",
                    models.TextField(blank=True, help_text="Generated story content"),
                ),
                (
                    "character_description",
                    models.TextField(
                        blank=True, help_text="Generated character description"
                    ),
                ),
                (
                    "character_image_path",
                    models.CharField(
                        blank=True, help_text="Path to character image", max_length=500
                    ),
                ),
                (
                    "background_image_path",
                    models.CharField(
                        blank=True, help_text="Path to background image", max_length=500
                    ),
                ),
                (
                    "composed_image_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to final composed image",
                        max_length=500,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded audio file",
                        null=True,
                        upload_to="temp_audio/",
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Generated Story",
                "verbose_name_plural": "Generated Stories",
                "ordering": ["-created_at"],
            },
        ),
    ]
